Repository BaderEddineOuaich/time_ago_provider, pull requests merged in 2020-10, with the labels that each got.

#7 Create turkish.dart
  lib/src/languages/turkish.dart
Labels: enhancement

#8 Turkish support files added.
  lib/src/time_ago_provider.dart
Labels: bug

#9 A little translation mistake in Turkish Language.
  lib/src/languages/turkish.dart
Labels: translation

#10 Add Portuguese Language
  lib/src/languages/portuguese.dart
Labels: translation
